config/routes.rb
Rails.application.routes.draw do
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "root#root"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
    validates_presence_of :name
    validates :rating, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to :root }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { redirect_to :root }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :rating)
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def root
    @items = Item.all
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% if Rails.env.development? %>
      <% console %>
    <% end %>
  </body>
</html>

app/views/root/root.html.erb
<p align="center" style="padding-top: 2rem">
  <a href="//architect.io" target="blank">
    <img
      src="https://cdn.architect.io/logo/horizontal.png"
      width="320"
      alt="Architect Logo"
    />
  </a>
</p>

<div style="margin: 40px">
  <div class="container">
    <h1>Favorite Movie</h1>
    <div class="user_inputs">
      <%= form_for Item.new, :url => items_path, :html => {:method => :post}  do |form| %>
        <%= form.text_field :name, class: "form-control", :placeholder => "Name*"  %>
        <%= form.number_field :rating, class: "form-control", :placeholder => "Rating 1-5*"  %>
        <div style="margin-top: 5px">
          <%= form.submit %>
        </div>
      <% end %>
    </div>

    <div style="margin-bottom: 10px" id="itemList">
      <% if @items.length > 0 %>
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Rating</th>
            </tr>
          </thead>
          <tbody>
            <% @items.each do |item| %>
              <tr>
                <td><%= item.name %></td>
                <td><%= item.rating %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>No entries found</p>
      <% end %>
    </div>
  </div>
</div>